version: '3'

services:
  web:
    build: .
    command: gunicorn crowd.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env 
